loadgen/contract-faucet.js
Some small changes to switch to the new amountMath (old version has been deprecated and will be deleted soon).
=> chore: use new amountMath

.github/workflows/lint-test.yml
https://github.com/Agoric/agoric-sdk/pull/3140 dropped support for Node 12 in the SDK, and the root `package.json` was updated accordingly. This causes CI tests running on that version to fail here because of the dependency, so this PR similarly removes the CI job.
=> Drop support for Node 12

.dockerignore, Dockerfile, README-extended.md, README.md, loadgen/agent-trade-amm.js, loadgen/loop.js, runner/lib/main.js, runner/lib/tasks/testnet.js, start.sh
This PR updates the AMM task to provision the fee purse (subsuming #16), and updates the Readme with clear instructions for how to setup a loadgen running against testnet. Existing details on how the automated runner works have been moved to an extended readme file (2 separate commits for easier diffing).
The initial RUN split is currently set to use 1/3 for fees and 1/3 to buy BLD. We can update as necessary.
=> Testnet compatibility

runner/lib/main.js, start.sh
Small fixes to automate running chain monitor through the runner under more scenarios:
- Shared docker volume for source (to avoid recompiling the SDK every start)
- restarting chain only monitor with shared stage duration
=> Testnet runner fixes

loadgen/database.rules.json, loadgen/firebase/admin.js, loadgen/firebase/client.js, loadgen/firebase/database.rules.json, loadgen/firebase/firebase.json
- Sets up security rules to prevent unexpected changes to the orchestration data. The security rules are currently manually deployed through the console.
- Improve the setup of onDisconnect and add a keep alive mechanism to hopefully make loadgen clients data more reliable (I saw some "cycles" zombie entries, but strangely no client marked connected when they're not)
- Fix a couple issues in the orchestrator script
=> Loadgen security rules and better disconnect handling

loadgen/firebase/admin.js, loadgen/firebase/admin/config.js, loadgen/firebase/admin/helpers.js, loadgen/firebase/admin/index.js, loadgen/firebase/admin/package.json, loadgen/firebase/auth.js, loadgen/firebase/database.rules.json, loadgen/firebase/firebase.json, loadgen/orchestrate.js, loadgen/package.json, package.json, yarn.lock
This PR moves the loadgen orchestrator from an active script to stateless cloud functions.
Moves the orchestration state to Firebase storage. Keep ability to run stateless cloud functions as local script for easier debugging, without relying on emulator (both could run at the same time if they produce the same results).
The current way to tweak the loadgen knobs is to modify the values under `loadgen/admin/config` in the Firebase console.
TODO:
- Add CLI to tweak loadgen knobs
- Add HTTP triggers to reset computed values if they get out of sync (currently deleting them in the console or running the orchestrator script should both work).
=> feat(loadgen): Cloud orchestrator

runner/jsconfig.json, runner/lib/helpers/module.js, runner/lib/main.js, runner/lib/monitor/loadgen-monitor.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/shared-loadgen.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts, runner/package.json, yarn.lock
When I started regenerating the corpus of stats, I realized that the runner and loadgen did not run correctly against both older and newer SDK revisions (I was working against a somewhat outdated version).
In particular:
- Newer SDKs do not provide sufficient RUN/BLD to pay for Zoe fees and let the loadgen complete multiple cycles
- When killing the chain while under load (middle of a mailbox delivery), the validator node would stall on restart (https://github.com/Agoric/agoric-sdk/issues/4115)
- The stats of shorter stages would be impacted by increasing setup time that was performed during stage 1, causing these stats to be unreliable
The first issue is fixed by provisioning and starting the local-solo manually, which required hooking into the cli to figure out the right path to use …
=> Make runner compatible with wide range of SDK revisions

.dockerignore, Dockerfile, library-scripts/go-debian.sh, loadgen/firebase/admin/package.json, loadgen/firebase/firebase.json, runner/lib/entrypoint.js, runner/lib/helpers/async.d.ts, runner/lib/helpers/async.js, runner/lib/helpers/elided-buffer-line-transform.d.ts, runner/lib/helpers/elided-buffer-line-transform.js, runner/lib/main.js, runner/lib/monitor/chain-monitor.js, runner/lib/monitor/slog-monitor.js, runner/lib/tasks/helpers.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/shared-env-info.js, runner/lib/tasks/shared-loadgen.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts, runner/package.json, start.sh, yarn.lock
This PR updates the runner with a grab bag of fixes I did while making the stats generation more robust, and working on moving the provisioning check of the client for a testnet chain to the setup phase.
Checking earlier allows the testnet loadgen to pause before starting and wait until the client is provisioned, instead of requiring action after the start, which may be a while when catching up to an existing chain. I originally started adding the ability to auto provision a client for a local testnet (based on the keys and the same logic as a local-chain), but reverted course and moved that functionality into a separate script used by the integration test (see https://github.com/Agoric/agoric-sdk/pull/4256).
List of various fixes:
- Update to node 16 and Debian bullseye (with fallback to …
=> Better runner compatibility with testnet

runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js
https://github.com/Agoric/testnet-load-generator/pull/44/commits/778b4e8cd66bb5aa268f5a5abc7059516742983f introduced the feature of saving the slog file of the ag-solo. However generating a slog file was only introduced in the SDK by https://github.com/Agoric/agoric-sdk/pull/3611, so solos from older SDK would never open the slog FIFO, and the solo would have been considered as never fully started, ultimately timing out and failing.
This change makes the solo slog optional, and conditionally pipes the streams to avoid failures.
=> Compatibility with older SDK without solo slog

runner/bin/regen-perf.js, runner/lib/main.js, runner/lib/stats/blocks.js, runner/lib/stats/cycles.js, runner/lib/stats/helpers.d.ts, runner/lib/stats/helpers.js, runner/lib/stats/run.js, runner/lib/stats/stages.js, runner/lib/stats/types.d.ts
As requested by @Tartuffo, this change refactors the stats summary generation and adds p95 percentiles to the values for which we generated averages.
I've also added a script which parses a `perf.jsonl` stream and rewrites the stats, regenerating the summaries. This helped me verify that the new summary logic didn't result in any real changes (just a few differences due to rounding).
```sh
for i in manual-*
do 
echo $i
diff \
<(tail -q -n 1 $i/perf.jsonl | jq '.stats') \
<(cat $i/perf.jsonl | ../runner/bin/regen-perf.js | tail -q -n 1 | jq '.stats')
done
```
I also fixed a bug where the stage stats summaries were not generated for a failing stage.
Related to: https://github.com/Agoric/testnet-load-generator/pull/36/commits/5d4034af7bee15c9d9698fec868ed499464b49d1 in …
=> Add p95 to stats summaries

README.md, loadgen/config.js, loadgen/contract/agent-create-vault.js, loadgen/contract/agent-trade-amm.js, loadgen/contract/petnames.js, loadgen/loop.js, loadgen/task-create-vault.js, loadgen/task-trade-amm.js
https://github.com/Agoric/agoric-sdk/pull/4387 removed BLD as collateral, so the loadgen needs to use another token to perform its work. USDC seem available across all revisions, so use that instead.
=> Switch BLD->USDC

loadgen/contract/agent-create-vault.js
Fall back to `multiplyBy`
Handle removal of deprecated API in https://github.com/Agoric/agoric-sdk/pull/4467
=> fix(loadgen): use `floorMultiplyBy`

.github/workflows/integration.yml, start.sh
This PR adds an integration test of the loadgen runner with the latest version of the `agoric-sdk`. While it uses a `local-chain` instead of multinode chain like the integration test in the `agoric-sdk` repo (see https://github.com/Agoric/agoric-sdk/pull/4256), besides setup most of the loadgen logic is shared, so it should be enough to gain confidence that a change in this repo will not inadvertently break `agoric-sdk`'s CI.
=> Add CI integration job

runner/lib/main.js, runner/lib/monitor/chain-monitor.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts
While trying to debug https://github.com/Agoric/agoric-sdk/issues/4473, I realized the state dirs were not backed up on the last restart failure. That's because for historical reasons, the state dirs were only returned as part of a successful result of the tasks, which we didn't even get to.
This refactors the runner to move the state dir info to the setup stage, and backup out of the stage logic.
=> Save storage even when not all tasks ran

runner/lib/helpers/stream.js, runner/lib/tasks/testnet.js
A chain in follow mode (`testnet`) may reach a concensus failure. In those cases the process does not stop, as the cosmos layer stay up answering RPC requests, but no further progress is made.
This change detect this case by following the chain node's stderr, and failing the task immediately if a `CONSENSUS FAILURE` is printed.
=> fix(runner): fail fast on concensus failure

.github/workflows/integration.yml, runner/lib/tasks/testnet.js
Launching a follower node in consensus mode with debug enabled causes consensus failures (see https://github.com/Agoric/agoric-sdk/issues/4506).
Until we have a consensus preserving verbose mode, remove `DEBUG` env for the testnet chain task.
Fixes https://github.com/Agoric/agoric-sdk/issues/4473
=> fix(runner): disable testnet chain monitor debug mode

Dockerfile, library-scripts/go-debian.sh, loadgen/loop.js, runner/lib/helpers/buffer-line-transform.d.ts, runner/lib/helpers/buffer-line-transform.js, runner/lib/helpers/child-process.js, runner/lib/helpers/elided-buffer-line-transform.d.ts, runner/lib/helpers/line-stream-transform.d.ts, runner/lib/helpers/types.d.ts, runner/lib/main.js, runner/lib/stats/blocks.js, runner/lib/stats/cycles.js, runner/lib/stats/helpers.d.ts, runner/lib/stats/run.js, runner/lib/stats/stages.js, runner/lib/stats/types.d.ts, runner/lib/tasks/local-chain.js, runner/lib/tasks/shared-loadgen.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts, scripts/run-daily-perf.sh, scripts/run-manual.sh
Change the default stage times for the base runner and daily perf tests, and standardize the manual test times. Fixes #66 
Capture the stage shutdown time in stats, and generate the last 100 blocks summary to only consider blocks before winddown. Fixes #65 
Update docker image scripts to incorporate an upstream fix.
Drive by fixes of some outdated eslint disables.
=> Tweak runner config and stats

runner/lib/helpers/stream.js, runner/lib/tasks/local-chain.js
Use the agoric cli only in the setup task to initialize the home / state dir. Launch the chain task directly using the `cosmosChain` binary instead of using the cli, making `local-chain` more similar to `testnet`.
If the cli doesn't support `--no-restart` for `local-chain` (feature pending), kill the chain immediately before it does any actual work.
=> Setup chain in setup task for local-chain

loadgen/config.js, loadgen/contract/agent-create-vault.js, loadgen/contract/agent-prepare-loadgen.js, loadgen/contract/agent-tap-faucet.js, loadgen/contract/agent-trade-amm.js, loadgen/contract/allValues.js, loadgen/contract/display.js, loadgen/contract/fallback.js, loadgen/contract/mintHolder.js, loadgen/contract/package.json, loadgen/contract/petnames.js, loadgen/loop.js, loadgen/package.json, loadgen/prepare-loadgen.js, loadgen/task-create-vault.js, loadgen/task-tap-faucet.js, loadgen/task-trade-amm.js, loadgen/types.js, runner/lib/main.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js, scripts/common-queue.sh, scripts/run-manual.sh, yarn.lock
Closes #69 
Refs https://github.com/Agoric/agoric-sdk/issues/4634
Best reviewed commit-by-commit
https://github.com/Agoric/agoric-sdk/pull/4541 removed the AMM, VaultFactory and demo assets from the default bootstrap. While the demo config does have the AMM and VaultFactory enabled, it doesn't contain any assets the loadgen could use for its tasks.
https://github.com/Agoric/agoric-sdk/pull/4641 added the ability for the loadgen to bless an asset as usable with vaults. This PR mainly updates the loadgen to create its own asset, create an AMM pool, fund it with that asset and some RUN, and bless the asset for usage with the VaultFactory.
This PR ends up as a complete rewrite of the task prepare steps, and make major changes to the tasks themselves. Some noteworthy changes:
- Remove sending …
=> Rewrite loadgen to use a dedicated asset

runner/lib/monitor/chain-monitor.js, runner/lib/monitor/slog-monitor.js
Fixes #77 
Handle the `terminate` event, and make sure to exclude no-longer running vats in the startup check.
Drive-by improvement of chain monitor logging
=> Handle vat termination

runner/lib/main.js, runner/lib/tasks/helpers.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts
Add the ability to save traces for the kvstore, xsnap and the swingstore.
Rename the storage tarball filename for consistency.
chain swingstore and client xsnap and swingstore traces rely on https://github.com/Agoric/agoric-sdk/pull/5228, but being env additions, it's backwards compatible to add to loadgen independently.
=> feat(runner): Support chain and client traces

runner/lib/monitor/slog-monitor.js
Handle the slog JSON shape change introduced in https://github.com/Agoric/agoric-sdk/pull/5599
This does not address the potential time drift between the now non-monotonic `time` of the slog vs monotonic "how behind are we processing the slog" time source, which is informational only. This will be addressed in a future change.
=> fix(runner): handle new slog line shape

loadgen/contract/agent-create-vault.js, loadgen/contract/agent-prepare-loadgen.js, loadgen/contract/agent-tap-faucet.js, loadgen/task-create-vault.js, loadgen/task-tap-faucet.js, loadgen/types.js
Refs: https://github.com/Agoric/agoric-sdk/pull/5735
Handles deprecation of `E(vaultFactoryPublicFactet).makeLoanInvitation()`.
Drive by fix of some typings.
Manually tested against agoric-sdk revisions:
- `4cca7443` (current master)
- `e43902478` (https://github.com/Agoric/agoric-sdk/pull/4641) + moddable@`9a760a9` + xsnap-native@`3fc543d` (to incorporate fixes of https://github.com/Agoric/agoric-sdk/pull/5138 without which we now hit some anachrophobia on restart)
- `492769f2f` (Before change removing USDC)
=> feat(loadgen): Use collateral manager

loadgen/contract/agent-create-vault.js, loadgen/contract/agent-prepare-loadgen.js, loadgen/contract/agent-tap-faucet.js, loadgen/contract/agent-trade-amm.js, loadgen/contract/fallback.js, loadgen/task-create-vault.js, loadgen/task-trade-amm.js, loadgen/types.js, runner/lib/tasks/local-chain.js
https://github.com/Agoric/agoric-sdk/issues/5326 is renaming RUN -> IST. This PR refactors the loadgen to no longer hardcode `RUN`, and instead names anything related with "stable". Then it adds a dynamic fallback from IST to RUN for backwards compatibility.
Successfully tested locally the "local-chain" variant against the same revisions as https://github.com/Agoric/testnet-load-generator/pull/71, as well as the current master of agoric-sdk: `12e61941`. The "testnet" variant against the same agoric-sdk master revision is also passing, allowing a safe merge without breaking agoric-sdk's CI.
Tested against the [IST rename branch](https://github.com/Agoric/agoric-sdk/pull/5585) (`4800-unRUN`).
=> Refactor loadgen to handle IST

runner/lib/helpers/procsfs.js, runner/lib/main.js, runner/lib/monitor/loadgen-monitor.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts
Refs #41 
Attempt at supporting MacOS in the loadgen. Removes the hard `procfs` dependency at the cost of disabling the process monitor logic, and some fallback mechanisms when not present.
Unfortunately it looks like a full loadgen still fails, some issue with the solo stalling, possibly related to the slog file. Since the issue may be unrelated to the loadgen, landing these changes.
Drive-by type/lint fixes
=> feat(runner): handle missing procfs

loadgen/contract/agent-prepare-loadgen.js
No reason to rely on this, as there are arguments to make this "feature" go away in the future: https://github.com/endojs/endo/issues/1253
=> fix(loadgen): remove bound usages of E proxy methods

runner/lib/main.js, runner/lib/monitor/slog-monitor.js
[Rework of cosmic-swingset to change action processing](https://github.com/Agoric/agoric-sdk/issues/6210) will always nest `cosmic-swingset-run-start` and `cosmic-swingset-run-finish` slog events in the `end-block`, so look at `computrons` to decide if the block was actually empty, which really should have been the case a long time ago.
=> fix(runner): handle empty blocks with nest slog lines

runner/lib/monitor/slog-monitor.js
With https://github.com/Agoric/agoric-sdk/pull/6442 we're only preloading at init the first 25 vats, and then dynamically loading any vat on first delivery.
As detailed in https://github.com/Agoric/agoric-sdk/pull/6520/, we observed an integration test failing on stage 2 (restart with no load). I tracked it to replay deliveries, which miss a `crankNum` and happen during a block (aka after init).
With this PR, we now handle replay deliveries in the loadgen runner slog monitor.
=> fix(runner): handle replay after init

scripts/common-queue.sh, scripts/run-daily-perf.sh
Benchmark machine keeps running out of space. Cleanup storage on successful runs.
=> feat(scripts): clean storage on successful daily run

.github/workflows/integration.yml, loadgen/contract/agent-prepare-loadgen.js
Apparently all the fallback logic was there to handle a missing AMM, with just one tiny mistake.
This does not (yet) attempt to setup the vault without AMM.
`agoric-sdk` will also need to be updated to not try to run the amm & vault tasks (as that will fail without the agents being installed) but similarly run only the faucet task for now.
#agoric-sdk-branch: 7055-exciseAMM
=> fix: handle missing AMM

runner/lib/main.js, runner/lib/stats/types.d.ts, runner/lib/tasks/testnet.js
This change adds an option in preparation of https://github.com/Agoric/agoric-sdk/issues/3769 to allow the testnet runner to join using a state-sync snapshot instead of catching up from genesis. This will be exercised in the CI deployment integration test once https://github.com/Agoric/agoric-sdk/compare/mhofman/5542-export-state-sync gets merged.
I have locally verified that these changes together are sufficient for that test to use state-sync (using agoric-sdk's `run-deployment-integration.sh` script)
=> feat(runner): Enable starting testnet follower from state-sync

.github/workflows/integration.yml, runner/lib/tasks/testnet.js
Tweak the "testnet" mode of the loadgen to connect to an instagoric created devnet which only exposes a `network-config` but not a `genesis.json`.
Locally verified that integration tests in `agoric-sdk` still run.
=> feat(runner): support instagoric devnet

runner/lib/main.js, runner/lib/tasks/local-chain.js, runner/lib/tasks/testnet.js
This updates the loadgen in the following ways:
- Use SIGINT to stop the chain process, which allows it to cleanly shutdown without errors. See https://github.com/Agoric/agoric-sdk/pull/7559
- Disables the process monitor as it's currently incompatible with multiple process per vat, which happens transiently when a worker is forced reloaded from snapshot. See https://github.com/Agoric/agoric-sdk/issues/6943
=> fix(runner): cleaner chain shutdown and disable process monitor

runner/lib/tasks/local-chain.js
Sends the coins to the solo's address before provisioning its swingset account in the local-chain scenario. This is more equivalent to the CI environment which sends the coins to the address the same transaction as the message provisioning the account, causing swingset to see the updated balance when the account gets created.
=> fix(runner): re-order local provision

.github/workflows/integration.yml, README-extended.md, runner/lib/main.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts, runner/package.json, runner/yarn.lock
This PR adds a new task `spwanAcceptance` which will run a follower for a chain and can be somewhat controlled by the validator on when to stop. More details in the updated README.
=> feat: Monitoring follower

.github/workflows/integration.yml, .github/workflows/lint-test.yml, runner/lib/tasks/testnet.js
Accept trusted block info from the network-config so that an integration test can provide a recent known block info. This could be useful in case the old block picked by default may have gotten pruned.
See https://github.com/Agoric/agoric-sdk/pull/11249
=> feat(runner): handle trusted block info in network config

.github/workflows/integration.yml, .github/workflows/lint-test.yml, _agstate/agoric-servers/package.json, loadgen/contract/package.json, loadgen/package.json, package.json, runner/lib/entrypoint.js, runner/lib/helpers/module.js, runner/lib/main.js, runner/lib/tasks/testnet.js, runner/lib/tasks/types.d.ts, start.sh, yarn.lock
Addressed comments from https://github.com/Agoric/testnet-load-generator/pull/119 which were left unaddressed due to auto merge
=> chore: Monitoring follower unaddressed comments
